import { LayoutWithSidebar } from './components';
import './global.css';
import { usePathname } from 'next/navigation';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // This hook only works in client components, so wrap the layout in a Client Component
  return (
    <html lang="en">
      <body>
        <LayoutWithSidebar>{children}</LayoutWithSidebar>
      </body>
    </html>
  );
}
