import './global.css';
import { LayoutWithSidebar } from './components';
import { AuthGuard } from './components/auth-guard/AuthGuard';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>
          <LayoutWithSidebar>{children}</LayoutWithSidebar>
        </AuthGuard>
      </body>
    </html>
  );
}

// Move AuthGuard to a separate client component file!
