name: Build and deploy Node.js app to Azure Web App - backendecopote

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # or '20.x' for better Azure compatibility

      - name: Install dependencies
        run: npm install

      - name: Generate database
        run: npm run database:generate

      - name: Build backend
        run: npx nx build backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Use subscription ID for login
        with:
          app-name: 'backendecopote'
          slot-name: 'Production'
          package: dist/apps/backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
